name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [17.x, 16.x, 15.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Codecov
      uses: codecov/codecov-action@v1

  benchmark:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [17.x, 16.x, 15.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install h2o
      run: |
        sudo apt-get install h2o
    - name: Build project
      run: |
        npm install
        npm run build --if-present
    - name: Start server
      run: |
        h2o -c h2o.conf &
        sleep 1
    - name: Run benchmark
      run: node benchmark.js
